// AUTO-GENERATED AUDIO MAP FROM ELEVENLABS TTS
export const audioMap = {
  "Alex flipped a mystery coin 10 times and got 7 heads. Does that mean the coin is unfair? How can we find out without guessing?": "/assets/audio/wonder_intro.mp3",
  "Alex flipped a coin at the Chance Corner carnival booth. Every single flip is called a trial. The outcome is what lands on top: Heads or Tails!": "/assets/audio/story_s1_text.mp3",
  "To keep track of many flips, Maya uses tallies. Grouping tallies in fives makes counting fast and easy!": "/assets/audio/story_s2_text.mp3",
  "Frequency is simply the number of times an event occurred. Alex counted seven heads, so the frequency of heads is seven!": "/assets/audio/story_s3_text.mp3",
  "Relative frequency is the experimental probability! We calculate it by dividing the frequency by total trials. Seven out of ten is zero point seven or seventy percent.": "/assets/audio/story_s4_text.mp3",
  "At the Dice Dojo, Alex rolls a six-sided die. Short experiments can have surprising results, but every face should come up equally often over time!": "/assets/audio/story_s5_text.mp3",
  "Maya tried ten flips and got four heads, while Alex got seven heads. Repeat experiments often give different results because of random chance!": "/assets/audio/story_s6_text.mp3",
  "As the number of trials increases to one hundred or one thousand, the relative frequency settles near a steady value. This is the Law of Large Numbers!": "/assets/audio/story_s7_text.mp3",
  "We can use experimental probability to predict future outcomes. Expected count equals probability times total trials!": "/assets/audio/story_s8_text.mp3",
  "What did you learn about experimental probability? Explain it to Leo with an example!": "/assets/audio/reflect_prompt.mp3",
  "Congratulations! You completed the Chance Quest Experimental Probability lesson!": "/assets/audio/reflect_complete.mp3",
  "Awesome job! You got it right!": "/assets/audio/feedback_correct.mp3",
  "Not quite! Check the explanation and try again!": "/assets/audio/feedback_wrong.mp3",
  "Out of hearts! Don't worry, experimental probability takes practice. Try again!": "/assets/audio/out_of_hearts.mp3",
  "Welcome to Station 1: Alex's Carnival Coin Flip! Flip the coin at least 10 times, then calculate the live experimental probability of heads.": "/assets/audio/sim_st1_intro.mp3",
  "Experimental Probability equals Heads Frequency divided by Total Flips. Multiply decimal by 100 for percentage!": "/assets/audio/sim_st1_hint.mp3",
  "Awesome job! You calculated the experimental probability of heads for Alex's coin!": "/assets/audio/sim_st1_feedback.mp3",
  "Welcome to Station 2: Maya's Dice Dojo Booth! Roll the die at least 12 times and track frequencies for all six faces.": "/assets/audio/sim_st2_intro.mp3",
  "Count how many times face 6 landed, then divide by total rolls.": "/assets/audio/sim_st2_hint.mp3",
  "Great job! You calculated the experimental probability for face 6 at the Dice Dojo!": "/assets/audio/sim_st2_feedback.mp3",
  "Welcome to Station 3: Carnival Color Prize Wheel! Spin the wheel at least 10 times and calculate the relative frequency of landing on Blue.": "/assets/audio/sim_st3_intro.mp3",
  "Divide Blue sector count by total spins to find the relative frequency.": "/assets/audio/sim_st3_hint.mp3",
  "Awesome spinning! You calculated relative frequency for the carnival prize wheel!": "/assets/audio/sim_st3_feedback.mp3",
  "Welcome to Station 4: Law of Large Numbers Lab! Test short versus large trial batches to see how relative frequency settles near 50 percent.": "/assets/audio/sim_st4_intro.mp3",
  "As total trials grow larger, random variation decreases.": "/assets/audio/sim_st4_hint.mp3",
  "Bingo! As the number of trials increases, experimental probability settles near the true value!": "/assets/audio/sim_st4_feedback.mp3",
  "Welcome to Station 5: Carnival Prediction Engine! Use win probability P and total trials N to calculate Expected Count E equals P times N.": "/assets/audio/sim_st5_intro.mp3",
  "Expected count equals win probability P multiplied by total trials N.": "/assets/audio/sim_st5_hint.mp3",
  "Fantastic prediction! Expected count equals probability times total trials!": "/assets/audio/sim_st5_feedback.mp3",
  "Alex flipped a coin 10 times at the carnival. What counts as ONE single trial?": "/assets/audio/w1_q1_p.mp3",
  "One flip is a single trial. Heads or Tails is the outcome.": "/assets/audio/w1_q1_h.mp3",
  "Maya rolled a six-sided die once. What is the outcome of this trial?": "/assets/audio/w1_q2_p.mp3",
  "The outcome is the top number that lands facing up after rolling.": "/assets/audio/w1_q2_h.mp3",
  "Lucas flipped a coin 20 times. How many total trials were conducted in this experiment?": "/assets/audio/w1_q3_p.mp3",
  "The total number of trials is 20, because each flip counts as one trial.": "/assets/audio/w1_q3_h.mp3",
  "Sophia recorded landing on Heads during a coin flip. Is Heads a trial or an outcome?": "/assets/audio/w1_q4_p.mp3",
  "Heads is an outcome, which is the result of a single trial.": "/assets/audio/w1_q4_h.mp3",
  "Ethan spun a four-color wheel once. How many possible outcomes can this single trial have?": "/assets/audio/w1_q5_p.mp3",
  "There are four possible outcomes, one for each color sector.": "/assets/audio/w1_q5_h.mp3",
  "Oliver drew one marble from a bag. What is the trial in this activity?": "/assets/audio/w1_q6_p.mp3",
  "Drawing one marble from the bag is the single trial.": "/assets/audio/w1_q6_h.mp3",
  "Emma flipped a coin 50 times. What does each individual flip represent?": "/assets/audio/w1_q7_p.mp3",
  "Each individual flip represents one single trial.": "/assets/audio/w1_q7_h.mp3",
  "Alex wants to test if a coin is fair. What is an event in probability?": "/assets/audio/w1_q8_p.mp3",
  "An event is a specific outcome or set of outcomes we are interested in tracking.": "/assets/audio/w1_q8_h.mp3",
  "Maya rolls a die and gets a 5. Is getting a 5 considered a trial, an outcome, or total flips?": "/assets/audio/w1_q9_p.mp3",
  "Getting a 5 is an outcome of rolling the die.": "/assets/audio/w1_q9_h.mp3",
  "Sam flips a coin 15 times. Which of the following describes the complete set of possible outcomes for one flip?": "/assets/audio/w1_q10_p.mp3",
  "The complete set of possible outcomes for a standard coin is Heads or Tails.": "/assets/audio/w1_q10_h.mp3",
  "Alex recorded coin flip tallies as 3 groups of 5 plus 2 extra tallies. What is the frequency of Heads?": "/assets/audio/w2_q1_p.mp3",
  "Multiply 3 by 5 to get 15, then add 2 extra tallies for a total frequency of 17.": "/assets/audio/w2_q1_h.mp3",
  "Maya counted tallies for rolling a 6 as 4 groups of 5. What is the frequency of rolling a 6?": "/assets/audio/w2_q2_p.mp3",
  "4 groups of 5 equals 20 tallies in total.": "/assets/audio/w2_q2_h.mp3",
  "Sam flipped a coin and marked 2 groups of 5 plus 4 extra tallies. What is the frequency of Tails?": "/assets/audio/w2_q3_p.mp3",
  "2 groups of 5 plus 4 equals 14 tallies.": "/assets/audio/w2_q3_h.mp3",
  "Emma recorded 5 groups of 5 tallies for red marble draws. What is the total frequency?": "/assets/audio/w2_q4_p.mp3",
  "5 multiplied by 5 equals 25.": "/assets/audio/w2_q4_h.mp3",
  "Lucas marked 1 group of 5 plus 3 extra tallies for blue spinner landings. What is the frequency?": "/assets/audio/w2_q5_p.mp3",
  "1 group of 5 plus 3 extra tallies equals 8.": "/assets/audio/w2_q5_h.mp3",
  "Sophia counted 35 tallies in total. How many groups of 5 tallies is that?": "/assets/audio/w2_q6_p.mp3",
  "35 divided by 5 equals 7 groups of 5 tallies.": "/assets/audio/w2_q6_h.mp3",
  "Ethan recorded tallies as 2 groups of 5 plus 1 extra tally line. What is the count?": "/assets/audio/w2_q7_p.mp3",
  "2 times 5 plus 1 equals 11 tallies.": "/assets/audio/w2_q7_h.mp3",
  "Oliver tracks 4 groups of 5 tallies plus 3 extra lines for winning tickets. What is the total frequency?": "/assets/audio/w2_q8_p.mp3",
  "4 times 5 is 20, plus 3 equals 23.": "/assets/audio/w2_q8_h.mp3",
  "Alex recorded 10 tallies in total. How many full groups of 5 tallies were drawn?": "/assets/audio/w2_q9_p.mp3",
  "10 tallies equal 2 full groups of 5.": "/assets/audio/w2_q9_h.mp3",
  "Maya groups tallies in bundles of 5. Why are tally marks grouped in fives?": "/assets/audio/w2_q10_p.mp3",
  "Grouping tallies in fives makes counting large totals quick and error-free.": "/assets/audio/w2_q10_h.mp3",
  "Alex conducted 40 trials in total and recorded an event frequency of 12. What was the total number of trials conducted?": "/assets/audio/w3_q1_p.mp3",
  "The total number of trials conducted is N equals 40. The event frequency is 12.": "/assets/audio/w3_q1_h.mp3",
  "Maya flipped a coin 50 times and got 28 Heads. What is the frequency of Heads?": "/assets/audio/w3_q2_p.mp3",
  "The frequency is the count of how many times Heads occurred, which is 28.": "/assets/audio/w3_q2_h.mp3",
  "Sam rolled a die 60 times and recorded face 3 appearing 14 times. What is the value of n, the total trials?": "/assets/audio/w3_q3_p.mp3",
  "Total trials n equals the total number of die rolls, which is 60.": "/assets/audio/w3_q3_h.mp3",
  "Emma drew a marble 30 times and pulled a red marble 18 times. What is the event frequency f for red marbles?": "/assets/audio/w3_q4_p.mp3",
  "The frequency f is the number of times red was drawn, which is 18.": "/assets/audio/w3_q4_h.mp3",
  "Lucas conducted 100 trials and logged 45 successes. What is the difference between total trials and frequency?": "/assets/audio/w3_q5_p.mp3",
  "Total trials n is 100, while frequency f is 45. The difference is 55 non-successes.": "/assets/audio/w3_q5_h.mp3",
  "Sophia recorded 15 wins out of 50 game plays. Which number represents the event frequency f?": "/assets/audio/w3_q6_p.mp3",
  "The event frequency f is 15, the number of wins recorded.": "/assets/audio/w3_q6_h.mp3",
  "Ethan rolled a die 25 times and got face 6 five times. What is n, the total number of trials?": "/assets/audio/w3_q7_p.mp3",
  "The total number of trials n is 25.": "/assets/audio/w3_q7_h.mp3",
  "Oliver flipped a coin 80 times and recorded 42 Tails. What is the frequency of Tails?": "/assets/audio/w3_q8_p.mp3",
  "The frequency of Tails is 42.": "/assets/audio/w3_q8_h.mp3",
  "Alex conducted an experiment with 200 trials. If an event occurred 70 times, what is f?": "/assets/audio/w3_q9_p.mp3",
  "The frequency f is 70.": "/assets/audio/w3_q9_h.mp3",
  "Maya ran 30 trials in total. If the frequency of landing on Green is 9, what is the frequency of NOT landing on Green?": "/assets/audio/w3_q10_p.mp3",
  "Subtract 9 from 30 to get 21 trials that did not land on Green.": "/assets/audio/w3_q10_h.mp3",
  "Alex rolled a die 50 times and got a 6 on 10 rolls. What is the relative frequency of rolling a 6 as a fraction?": "/assets/audio/w4_q1_p.mp3",
  "Relative frequency equals frequency 10 divided by total 50, which simplifies to 1/5 or 0.20.": "/assets/audio/w4_q1_h.mp3",
  "Maya flipped a coin 20 times and got 12 Heads. What is the relative frequency of Heads as a decimal?": "/assets/audio/w4_q2_p.mp3",
  "Divide 12 by 20 to get 0.60, or 60 percent.": "/assets/audio/w4_q2_h.mp3",
  "Sam spun a wheel 25 times and landed on Red 5 times. What percentage of the spins landed on Red?": "/assets/audio/w4_q3_p.mp3",
  "5 divided by 25 equals 0.20, which is 20 percent.": "/assets/audio/w4_q3_h.mp3",
  "Emma conducted 100 trials and recorded 35 successful outcomes. What is the relative frequency as a percentage?": "/assets/audio/w4_q4_p.mp3",
  "35 out of 100 equals 35 percent.": "/assets/audio/w4_q4_h.mp3",
  "Lucas drew a marble 40 times and got Blue 10 times. What is the simplified fraction for the relative frequency of Blue?": "/assets/audio/w4_q5_p.mp3",
  "10 out of 40 simplifies to 1/4 or 0.25.": "/assets/audio/w4_q5_h.mp3",
  "Sophia spun a prize wheel 50 times and won 15 times. Express the relative frequency of winning as a decimal.": "/assets/audio/w4_q6_p.mp3",
  "15 divided by 50 equals 0.30.": "/assets/audio/w4_q6_h.mp3",
  "Ethan flipped a coin 25 times and got 15 Tails. What is the relative frequency of Tails as a fraction?": "/assets/audio/w4_q7_p.mp3",
  "15 out of 25 simplifies to 3/5.": "/assets/audio/w4_q7_h.mp3",
  "Oliver rolled a die 60 times and got face 1 twelve times. What is the relative frequency as a simplified fraction?": "/assets/audio/w4_q8_p.mp3",
  "12 out of 60 simplifies to 1/5.": "/assets/audio/w6_q1_h.mp3",
  "Alex completed 20 trials and got 7 successes. What is the relative frequency written as a decimal?": "/assets/audio/w4_q9_p.mp3",
  "7 divided by 20 equals 0.35.": "/assets/audio/w4_q9_h.mp3",
  "Maya conducted 50 trials and logged 22 outcomes of interest. What is the relative frequency as a percentage?": "/assets/audio/w4_q10_p.mp3",
  "22 divided by 50 equals 0.44, which is 44 percent.": "/assets/audio/w4_q10_h.mp3",
  "Alex flipped a coin 50 times and got 28 Heads. What is the experimental probability of getting TAILS as a simplified fraction?": "/assets/audio/w5_q1_p.mp3",
  "Tails count equals 50 minus 28, which is 22. 22 out of 50 simplifies to 11/25.": "/assets/audio/w5_q1_h.mp3",
  "Maya flipped a coin 20 times and got 8 Heads. What is the experimental probability of getting Heads as a simplified fraction?": "/assets/audio/w5_q2_p.mp3",
  "8 out of 20 simplifies to 2/5.": "/assets/audio/w7_q5_h.mp3",
  "Sam flipped a coin 100 times and recorded 54 Heads. What is P(Tails) as a decimal?": "/assets/audio/w5_q3_p.mp3",
  "Tails count is 100 minus 54, which equals 46. 46 out of 100 is 0.46.": "/assets/audio/w5_q3_h.mp3",
  "Emma flipped a coin 40 times and got 24 Tails. What is P(Heads) as a simplified fraction?": "/assets/audio/w5_q4_p.mp3",
  "Heads count is 40 minus 24, which equals 16. 16 out of 40 simplifies to 2/5.": "/assets/audio/w5_q4_h.mp3",
  "Lucas flipped a coin 50 times and got 30 Heads. What is P(Heads) expressed as a percentage?": "/assets/audio/w5_q5_p.mp3",
  "30 out of 50 equals 0.60, which is 60 percent.": "/assets/audio/w5_q5_h.mp3",
  "Sophia flipped a coin 25 times and recorded 10 Heads. What is P(Tails) as a simplified fraction?": "/assets/audio/w5_q6_p.mp3",
  "Tails count is 25 minus 10, which is 15. 15 out of 25 simplifies to 3/5.": "/assets/audio/w5_q6_h.mp3",
  "Ethan flipped a coin 80 times and got 48 Heads. What is P(Heads) as a simplified fraction?": "/assets/audio/w5_q7_p.mp3",
  "48 out of 80 simplifies to 3/5.": "/assets/audio/w5_q7_h.mp3",
  "Oliver flipped a coin 100 times and got 45 Heads. What is P(Tails) as a percentage?": "/assets/audio/w5_q8_p.mp3",
  "Tails count is 100 minus 45, which is 55. 55 out of 100 is 55 percent.": "/assets/audio/w5_q8_h.mp3",
  "Alex flipped a mystery carnival coin 10 times and got 7 Heads. What is P(Heads) as a decimal?": "/assets/audio/w5_q9_p.mp3",
  "7 out of 10 equals 0.70.": "/assets/audio/w5_q9_h.mp3",
  "Maya flipped a fair coin 50 times and got 25 Heads. What is P(Heads) as a simplified fraction?": "/assets/audio/w5_q10_p.mp3",
  "25 out of 50 simplifies to 1/2.": "/assets/audio/w5_q10_h.mp3",
  "In 60 die rolls at the Dice Dojo, face 5 appeared 12 times. What is the experimental probability of rolling a 5 as a simplified fraction?": "/assets/audio/w6_q1_p.mp3",
  "Maya rolled a 6-sided die 30 times and got face 2 six times. What is the experimental probability of face 2 as a decimal?": "/assets/audio/w6_q2_p.mp3",
  "6 divided by 30 equals 0.20.": "/assets/audio/w6_q2_h.mp3",
  "Sam rolled a die 50 times and landed on an even number 28 times. What is P(even) as a simplified fraction?": "/assets/audio/w6_q3_p.mp3",
  "28 out of 50 simplifies to 14/25.": "/assets/audio/w6_q3_h.mp3",
  "Emma rolled a die 60 times and got face 6 ten times. How does this experimental probability compare to theoretical probability of 1/6?": "/assets/audio/w6_q4_p.mp3",
  "10 out of 60 equals 1/6, which matches the theoretical probability exactly!": "/assets/audio/w6_q4_h.mp3",
  "Lucas rolled a die 40 times and got a number greater than 4 twelve times. What is P(greater than 4) as a simplified fraction?": "/assets/audio/w6_q5_p.mp3",
  "12 out of 40 simplifies to 3/10.": "/assets/audio/w6_q5_h.mp3",
  "Sophia rolled a die 30 times and got face 1 three times. What is P(1) as a percentage?": "/assets/audio/w6_q6_p.mp3",
  "3 out of 30 equals 0.10, which is 10 percent.": "/assets/audio/w6_q6_h.mp3",
  "Ethan rolled a die 50 times and got face 4 nine times. What is P(4) as a decimal?": "/assets/audio/w6_q7_p.mp3",
  "9 divided by 50 equals 0.18.": "/assets/audio/w6_q7_h.mp3",
  "Oliver rolled a die 120 times and got face 3 twenty-four times. What is P(3) as a simplified fraction?": "/assets/audio/w6_q8_p.mp3",
  "24 out of 120 simplifies to 1/5.": "/assets/audio/w6_q8_h.mp3",
  "Alex rolled a die 60 times and landed on an odd number 33 times. What is P(odd) as a percentage?": "/assets/audio/w6_q9_p.mp3",
  "33 out of 60 equals 0.55, which is 55 percent.": "/assets/audio/w6_q9_h.mp3",
  "Why might rolling a die 10 times give different results than rolling it 600 times?": "/assets/audio/w6_q10_p.mp3",
  "Short experiments show random variation, while large trials settle near theoretical probabilities.": "/assets/audio/w6_q10_h.mp3",
  "Alex drew a marble 50 times with replacement and got Red 20 times. What percentage of draws were Red?": "/assets/audio/w7_q1_p.mp3",
  "20 divided by 50 equals 0.40, which is 40 percent.": "/assets/audio/w7_q1_h.mp3",
  "Maya spun a 4-sector wheel 40 times and landed on Blue 16 times. What is P(Blue) as a simplified fraction?": "/assets/audio/w7_q2_p.mp3",
  "16 out of 40 simplifies to 2/5.": "/assets/audio/w7_q2_h.mp3",
  "Sam drew a chip from a bag 30 times and got Yellow 9 times. What is P(Yellow) as a decimal?": "/assets/audio/w7_q3_p.mp3",
  "9 divided by 30 equals 0.30.": "/assets/audio/w7_q3_h.mp3",
  "Emma spun a spinner 50 times and landed on Green 15 times. What is P(Green) as a percentage?": "/assets/audio/w7_q4_p.mp3",
  "15 divided by 50 equals 0.30, which is 30 percent.": "/assets/audio/w7_q4_h.mp3",
  "Lucas drew a card 20 times with replacement and got a Star card 8 times. What is P(Star) as a simplified fraction?": "/assets/audio/w7_q5_p.mp3",
  "Sophia spun a prize wheel 100 times and got Gold 12 times. What is P(Gold) as a decimal?": "/assets/audio/w7_q6_p.mp3",
  "12 out of 100 equals 0.12.": "/assets/audio/w7_q6_h.mp3",
  "Ethan drew a marble 50 times and got Blue 25 times. What is P(Blue) as a percentage?": "/assets/audio/w7_q7_p.mp3",
  "25 out of 50 equals 50 percent.": "/assets/audio/w7_q7_h.mp3",
  "Oliver spun a 5-color wheel 50 times and got Purple 10 times. What is P(Purple) as a simplified fraction?": "/assets/audio/w7_q8_p.mp3",
  "10 out of 50 simplifies to 1/5.": "/assets/audio/w7_q8_h.mp3",
  "Alex drew a tile 40 times and got a vowel 14 times. What is P(vowel) as a decimal?": "/assets/audio/w7_q9_p.mp3",
  "14 divided by 40 equals 0.35.": "/assets/audio/w7_q9_h.mp3",
  "What does drawing with replacement mean in a marble experiment?": "/assets/audio/w7_q10_p.mp3",
  "Drawing with replacement means putting the marble back before the next draw so total trials stay equal.": "/assets/audio/w7_q10_h.mp3",
  "Alex flipped a fair coin 10 times and got 8 Heads. Maya flipped the same coin 10 times and got 4 Heads. Why did their results differ?": "/assets/audio/w8_q1_p.mp3",
  "Short experiments naturally show random variation. That is completely normal!": "/assets/audio/w8_q1_h.mp3",
  "Two students rolled the exact same die 20 times each. Student A got five 6s and Student B got two 6s. Is the die broken?": "/assets/audio/w8_q2_p.mp3",
  "No, small sample sizes naturally produce short-term experimental variation.": "/assets/audio/w8_q2_h.mp3",
  "If Alex repeats a 10-flip coin experiment 5 times, should he expect identical results every time?": "/assets/audio/w8_q3_p.mp3",
  "No, random chance causes variations between short repeat experiments.": "/assets/audio/w8_q3_h.mp3",
  "Maya got 70% Heads in 10 flips. Sam got 40% Heads in 10 flips. What explains this difference?": "/assets/audio/w8_q4_p.mp3",
  "Random chance and variation in short trial samples.": "/assets/audio/w8_q4_h.mp3",
  "Why do repeat experiments with small trial counts vary from theoretical probability?": "/assets/audio/w8_q5_p.mp3",
  "Small sample sizes are sensitive to random chance fluctuations.": "/assets/audio/w8_q5_h.mp3",
  "Emma and Lucas each spin a wheel 10 times. Emma wins 3 times, Lucas wins 6 times. Is this variation expected?": "/assets/audio/w8_q6_p.mp3",
  "Yes, small sample numbers vary due to chance.": "/assets/audio/w8_q6_h.mp3",
  "Sophia flipped a coin 10 times and got 9 Heads. Does this prove the coin is definitely biased?": "/assets/audio/w8_q7_p.mp3",
  "Not necessarily, 10 flips is too small a sample to prove bias without more trials.": "/assets/audio/w8_q7_h.mp3",
  "What is the best way to reduce experimental variation between trial groups?": "/assets/audio/w8_q8_p.mp3",
  "Increase the number of trials in each experiment.": "/assets/audio/w8_q8_h.mp3",
  "Oliver got 0 Heads in 4 flips. Is this possible with a fair coin?": "/assets/audio/w8_q9_p.mp3",
  "Yes, in very short experiments, extreme variations can happen by chance.": "/assets/audio/w8_q9_h.mp3",
  "What does experimental variation teach us about small samples?": "/assets/audio/w8_q10_p.mp3",
  "Small samples can fluctuate significantly from the expected value.": "/assets/audio/w8_q10_h.mp3",
  "Which experiment provides a more reliable estimate of a coin's true probability of landing Heads?": "/assets/audio/w9_q1_p.mp3",
  "Flipping the coin 1,000 times provides a much more reliable estimate than flipping it 10 times.": "/assets/audio/w9_q1_h.mp3",
  "As total trials increase from 10 to 1,000, what happens to the experimental probability of a fair coin?": "/assets/audio/w9_q2_p.mp3",
  "It settles near the true theoretical value of 0.50 or 50 percent.": "/assets/audio/w9_q2_h.mp3",
  "What is the name of the rule stating that relative frequency settles near theoretical probability as trials grow large?": "/assets/audio/w9_q3_p.mp3",
  "This is known as the Law of Large Numbers.": "/assets/audio/w9_q3_h.mp3",
  "Alex compares 50 flips versus 500 flips. Which sample size has less random fluctuation?": "/assets/audio/w9_q4_p.mp3",
  "500 flips has less random fluctuation because larger samples stabilize relative frequency.": "/assets/audio/w9_q4_h.mp3",
  "Maya tested a die with 60 rolls and 600 rolls. Which experiment yields a relative frequency closer to 1/6?": "/assets/audio/w9_q5_p.mp3",
  "600 rolls will yield a relative frequency closer to 1/6.": "/assets/audio/w9_q5_h.mp3",
  "Why do scientists and pollsters prefer large sample sizes over small sample sizes?": "/assets/audio/w9_q6_p.mp3",
  "Larger sample sizes reduce experimental error and give more accurate estimates.": "/assets/audio/w9_q6_h.mp3",
  "If a coin is flipped 10,000 times, what relative frequency of Heads would you expect?": "/assets/audio/w9_q7_p.mp3",
  "Very close to 0.50 or 50 percent.": "/assets/audio/w9_q7_h.mp3",
  "Sam flipped a coin 10 times and got 80% Heads. What should he do to check if the coin is truly fair?": "/assets/audio/w9_q8_p.mp3",
  "Conduct many more flips, such as 500 or 1,000 trials, to see if relative frequency settles near 50%.": "/assets/audio/w9_q8_h.mp3",
  "What happens to the difference between experimental relative frequency and theoretical probability as N approaches infinity?": "/assets/audio/w9_q9_p.mp3",
  "The difference approaches zero.": "/assets/audio/w9_q9_h.mp3",
  "True or False: The Law of Large Numbers guarantees exact results in short 5-flip experiments.": "/assets/audio/w9_q10_p.mp3",
  "False. The Law of Large Numbers applies as the number of trials becomes very large.": "/assets/audio/w9_q10_h.mp3",
  "A carnival game has an experimental win probability of P = 0.40. If Alex plays N = 200 times, how many wins should be expected?": "/assets/audio/w10_q1_p.mp3",
  "Expected Count equals P times N, which is 0.40 multiplied by 200, giving 80 expected wins.": "/assets/audio/w10_q1_h.mp3",
  "The probability of winning a prize is P = 0.25. If Maya plays 100 times, what is the expected number of wins?": "/assets/audio/w10_q2_p.mp3",
  "0.25 multiplied by 100 equals 25 expected wins.": "/assets/audio/w10_q2_h.mp3",
  "If P(Heads) = 0.50 and you flip a coin N = 500 times, how many Heads should you expect?": "/assets/audio/w10_q3_p.mp3",
  "0.50 multiplied by 500 equals 250 expected Heads.": "/assets/audio/w10_q3_h.mp3",
  "A spinner has P(Blue) = 0.30. In N = 300 spins, how many times do you expect to land on Blue?": "/assets/audio/w10_q4_p.mp3",
  "0.30 multiplied by 300 equals 90 expected Blue landings.": "/assets/audio/w10_q4_h.mp3",
  "Leo plays a arcade game with win probability P = 0.15 for N = 200 rounds. How many wins are expected?": "/assets/audio/w10_q5_p.mp3",
  "0.15 multiplied by 200 equals 30 expected wins.": "/assets/audio/w10_q5_h.mp3",
  "If P(Red) = 0.35 and Emma draws a marble N = 100 times with replacement, what is the expected count of Red marbles?": "/assets/audio/w10_q6_p.mp3",
  "0.35 multiplied by 100 equals 35 expected Red draws.": "/assets/audio/w10_q6_h.mp3",
  "A die has P(rolling a 6) = 1/6. If Lucas rolls the die 120 times, how many times should he expect to roll a 6?": "/assets/audio/w10_q7_p.mp3",
  "1/6 multiplied by 120 equals 20 expected 6s.": "/assets/audio/w10_q7_h.mp3",
  "If P(winning) = 0.50 in a carnival booth and 400 people play once, how many total winners are expected?": "/assets/audio/w10_q8_p.mp3",
  "0.50 multiplied by 400 equals 200 expected winners.": "/assets/audio/w10_q8_h.mp3",
  "Can actual experimental results differ slightly from the calculated expected count E = P × N?": "/assets/audio/w10_q9_p.mp3",
  "Yes, actual results can vary slightly around the expected count due to random chance.": "/assets/audio/w10_q9_h.mp3",
  "A game has P(win) = 0.70. If Oliver plays 50 times, what is the expected count of wins?": "/assets/audio/w10_q10_p.mp3",
  "0.70 multiplied by 50 equals 35 expected wins.": "/assets/audio/w10_q10_h.mp3",
  "wonder_intro": "/assets/audio/wonder_intro.mp3",
  "story_s1_text": "/assets/audio/story_s1_text.mp3",
  "story_s2_text": "/assets/audio/story_s2_text.mp3",
  "story_s3_text": "/assets/audio/story_s3_text.mp3",
  "story_s4_text": "/assets/audio/story_s4_text.mp3",
  "story_s5_text": "/assets/audio/story_s5_text.mp3",
  "story_s6_text": "/assets/audio/story_s6_text.mp3",
  "story_s7_text": "/assets/audio/story_s7_text.mp3",
  "story_s8_text": "/assets/audio/story_s8_text.mp3",
  "reflect_prompt": "/assets/audio/reflect_prompt.mp3",
  "reflect_complete": "/assets/audio/reflect_complete.mp3",
  "feedback_correct": "/assets/audio/feedback_correct.mp3",
  "feedback_wrong": "/assets/audio/feedback_wrong.mp3",
  "out_of_hearts": "/assets/audio/out_of_hearts.mp3",
  "sim_st1_intro": "/assets/audio/sim_st1_intro.mp3",
  "sim_st1_hint": "/assets/audio/sim_st1_hint.mp3",
  "sim_st1_feedback": "/assets/audio/sim_st1_feedback.mp3",
  "sim_st2_intro": "/assets/audio/sim_st2_intro.mp3",
  "sim_st2_hint": "/assets/audio/sim_st2_hint.mp3",
  "sim_st2_feedback": "/assets/audio/sim_st2_feedback.mp3",
  "sim_st3_intro": "/assets/audio/sim_st3_intro.mp3",
  "sim_st3_hint": "/assets/audio/sim_st3_hint.mp3",
  "sim_st3_feedback": "/assets/audio/sim_st3_feedback.mp3",
  "sim_st4_intro": "/assets/audio/sim_st4_intro.mp3",
  "sim_st4_hint": "/assets/audio/sim_st4_hint.mp3",
  "sim_st4_feedback": "/assets/audio/sim_st4_feedback.mp3",
  "sim_st5_intro": "/assets/audio/sim_st5_intro.mp3",
  "sim_st5_hint": "/assets/audio/sim_st5_hint.mp3",
  "sim_st5_feedback": "/assets/audio/sim_st5_feedback.mp3",
  "w1_q1_p": "/assets/audio/w1_q1_p.mp3",
  "w1_q1_h": "/assets/audio/w1_q1_h.mp3",
  "w1_q2_p": "/assets/audio/w1_q2_p.mp3",
  "w1_q2_h": "/assets/audio/w1_q2_h.mp3",
  "w1_q3_p": "/assets/audio/w1_q3_p.mp3",
  "w1_q3_h": "/assets/audio/w1_q3_h.mp3",
  "w1_q4_p": "/assets/audio/w1_q4_p.mp3",
  "w1_q4_h": "/assets/audio/w1_q4_h.mp3",
  "w1_q5_p": "/assets/audio/w1_q5_p.mp3",
  "w1_q5_h": "/assets/audio/w1_q5_h.mp3",
  "w1_q6_p": "/assets/audio/w1_q6_p.mp3",
  "w1_q6_h": "/assets/audio/w1_q6_h.mp3",
  "w1_q7_p": "/assets/audio/w1_q7_p.mp3",
  "w1_q7_h": "/assets/audio/w1_q7_h.mp3",
  "w1_q8_p": "/assets/audio/w1_q8_p.mp3",
  "w1_q8_h": "/assets/audio/w1_q8_h.mp3",
  "w1_q9_p": "/assets/audio/w1_q9_p.mp3",
  "w1_q9_h": "/assets/audio/w1_q9_h.mp3",
  "w1_q10_p": "/assets/audio/w1_q10_p.mp3",
  "w1_q10_h": "/assets/audio/w1_q10_h.mp3",
  "w2_q1_p": "/assets/audio/w2_q1_p.mp3",
  "w2_q1_h": "/assets/audio/w2_q1_h.mp3",
  "w2_q2_p": "/assets/audio/w2_q2_p.mp3",
  "w2_q2_h": "/assets/audio/w2_q2_h.mp3",
  "w2_q3_p": "/assets/audio/w2_q3_p.mp3",
  "w2_q3_h": "/assets/audio/w2_q3_h.mp3",
  "w2_q4_p": "/assets/audio/w2_q4_p.mp3",
  "w2_q4_h": "/assets/audio/w2_q4_h.mp3",
  "w2_q5_p": "/assets/audio/w2_q5_p.mp3",
  "w2_q5_h": "/assets/audio/w2_q5_h.mp3",
  "w2_q6_p": "/assets/audio/w2_q6_p.mp3",
  "w2_q6_h": "/assets/audio/w2_q6_h.mp3",
  "w2_q7_p": "/assets/audio/w2_q7_p.mp3",
  "w2_q7_h": "/assets/audio/w2_q7_h.mp3",
  "w2_q8_p": "/assets/audio/w2_q8_p.mp3",
  "w2_q8_h": "/assets/audio/w2_q8_h.mp3",
  "w2_q9_p": "/assets/audio/w2_q9_p.mp3",
  "w2_q9_h": "/assets/audio/w2_q9_h.mp3",
  "w2_q10_p": "/assets/audio/w2_q10_p.mp3",
  "w2_q10_h": "/assets/audio/w2_q10_h.mp3",
  "w3_q1_p": "/assets/audio/w3_q1_p.mp3",
  "w3_q1_h": "/assets/audio/w3_q1_h.mp3",
  "w3_q2_p": "/assets/audio/w3_q2_p.mp3",
  "w3_q2_h": "/assets/audio/w3_q2_h.mp3",
  "w3_q3_p": "/assets/audio/w3_q3_p.mp3",
  "w3_q3_h": "/assets/audio/w3_q3_h.mp3",
  "w3_q4_p": "/assets/audio/w3_q4_p.mp3",
  "w3_q4_h": "/assets/audio/w3_q4_h.mp3",
  "w3_q5_p": "/assets/audio/w3_q5_p.mp3",
  "w3_q5_h": "/assets/audio/w3_q5_h.mp3",
  "w3_q6_p": "/assets/audio/w3_q6_p.mp3",
  "w3_q6_h": "/assets/audio/w3_q6_h.mp3",
  "w3_q7_p": "/assets/audio/w3_q7_p.mp3",
  "w3_q7_h": "/assets/audio/w3_q7_h.mp3",
  "w3_q8_p": "/assets/audio/w3_q8_p.mp3",
  "w3_q8_h": "/assets/audio/w3_q8_h.mp3",
  "w3_q9_p": "/assets/audio/w3_q9_p.mp3",
  "w3_q9_h": "/assets/audio/w3_q9_h.mp3",
  "w3_q10_p": "/assets/audio/w3_q10_p.mp3",
  "w3_q10_h": "/assets/audio/w3_q10_h.mp3",
  "w4_q1_p": "/assets/audio/w4_q1_p.mp3",
  "w4_q1_h": "/assets/audio/w4_q1_h.mp3",
  "w4_q2_p": "/assets/audio/w4_q2_p.mp3",
  "w4_q2_h": "/assets/audio/w4_q2_h.mp3",
  "w4_q3_p": "/assets/audio/w4_q3_p.mp3",
  "w4_q3_h": "/assets/audio/w4_q3_h.mp3",
  "w4_q4_p": "/assets/audio/w4_q4_p.mp3",
  "w4_q4_h": "/assets/audio/w4_q4_h.mp3",
  "w4_q5_p": "/assets/audio/w4_q5_p.mp3",
  "w4_q5_h": "/assets/audio/w4_q5_h.mp3",
  "w4_q6_p": "/assets/audio/w4_q6_p.mp3",
  "w4_q6_h": "/assets/audio/w4_q6_h.mp3",
  "w4_q7_p": "/assets/audio/w4_q7_p.mp3",
  "w4_q7_h": "/assets/audio/w4_q7_h.mp3",
  "w4_q8_p": "/assets/audio/w4_q8_p.mp3",
  "w4_q8_h": "/assets/audio/w4_q8_h.mp3",
  "w4_q9_p": "/assets/audio/w4_q9_p.mp3",
  "w4_q9_h": "/assets/audio/w4_q9_h.mp3",
  "w4_q10_p": "/assets/audio/w4_q10_p.mp3",
  "w4_q10_h": "/assets/audio/w4_q10_h.mp3",
  "w5_q1_p": "/assets/audio/w5_q1_p.mp3",
  "w5_q1_h": "/assets/audio/w5_q1_h.mp3",
  "w5_q2_p": "/assets/audio/w5_q2_p.mp3",
  "w5_q2_h": "/assets/audio/w5_q2_h.mp3",
  "w5_q3_p": "/assets/audio/w5_q3_p.mp3",
  "w5_q3_h": "/assets/audio/w5_q3_h.mp3",
  "w5_q4_p": "/assets/audio/w5_q4_p.mp3",
  "w5_q4_h": "/assets/audio/w5_q4_h.mp3",
  "w5_q5_p": "/assets/audio/w5_q5_p.mp3",
  "w5_q5_h": "/assets/audio/w5_q5_h.mp3",
  "w5_q6_p": "/assets/audio/w5_q6_p.mp3",
  "w5_q6_h": "/assets/audio/w5_q6_h.mp3",
  "w5_q7_p": "/assets/audio/w5_q7_p.mp3",
  "w5_q7_h": "/assets/audio/w5_q7_h.mp3",
  "w5_q8_p": "/assets/audio/w5_q8_p.mp3",
  "w5_q8_h": "/assets/audio/w5_q8_h.mp3",
  "w5_q9_p": "/assets/audio/w5_q9_p.mp3",
  "w5_q9_h": "/assets/audio/w5_q9_h.mp3",
  "w5_q10_p": "/assets/audio/w5_q10_p.mp3",
  "w5_q10_h": "/assets/audio/w5_q10_h.mp3",
  "w6_q1_p": "/assets/audio/w6_q1_p.mp3",
  "w6_q1_h": "/assets/audio/w6_q1_h.mp3",
  "w6_q2_p": "/assets/audio/w6_q2_p.mp3",
  "w6_q2_h": "/assets/audio/w6_q2_h.mp3",
  "w6_q3_p": "/assets/audio/w6_q3_p.mp3",
  "w6_q3_h": "/assets/audio/w6_q3_h.mp3",
  "w6_q4_p": "/assets/audio/w6_q4_p.mp3",
  "w6_q4_h": "/assets/audio/w6_q4_h.mp3",
  "w6_q5_p": "/assets/audio/w6_q5_p.mp3",
  "w6_q5_h": "/assets/audio/w6_q5_h.mp3",
  "w6_q6_p": "/assets/audio/w6_q6_p.mp3",
  "w6_q6_h": "/assets/audio/w6_q6_h.mp3",
  "w6_q7_p": "/assets/audio/w6_q7_p.mp3",
  "w6_q7_h": "/assets/audio/w6_q7_h.mp3",
  "w6_q8_p": "/assets/audio/w6_q8_p.mp3",
  "w6_q8_h": "/assets/audio/w6_q8_h.mp3",
  "w6_q9_p": "/assets/audio/w6_q9_p.mp3",
  "w6_q9_h": "/assets/audio/w6_q9_h.mp3",
  "w6_q10_p": "/assets/audio/w6_q10_p.mp3",
  "w6_q10_h": "/assets/audio/w6_q10_h.mp3",
  "w7_q1_p": "/assets/audio/w7_q1_p.mp3",
  "w7_q1_h": "/assets/audio/w7_q1_h.mp3",
  "w7_q2_p": "/assets/audio/w7_q2_p.mp3",
  "w7_q2_h": "/assets/audio/w7_q2_h.mp3",
  "w7_q3_p": "/assets/audio/w7_q3_p.mp3",
  "w7_q3_h": "/assets/audio/w7_q3_h.mp3",
  "w7_q4_p": "/assets/audio/w7_q4_p.mp3",
  "w7_q4_h": "/assets/audio/w7_q4_h.mp3",
  "w7_q5_p": "/assets/audio/w7_q5_p.mp3",
  "w7_q5_h": "/assets/audio/w7_q5_h.mp3",
  "w7_q6_p": "/assets/audio/w7_q6_p.mp3",
  "w7_q6_h": "/assets/audio/w7_q6_h.mp3",
  "w7_q7_p": "/assets/audio/w7_q7_p.mp3",
  "w7_q7_h": "/assets/audio/w7_q7_h.mp3",
  "w7_q8_p": "/assets/audio/w7_q8_p.mp3",
  "w7_q8_h": "/assets/audio/w7_q8_h.mp3",
  "w7_q9_p": "/assets/audio/w7_q9_p.mp3",
  "w7_q9_h": "/assets/audio/w7_q9_h.mp3",
  "w7_q10_p": "/assets/audio/w7_q10_p.mp3",
  "w7_q10_h": "/assets/audio/w7_q10_h.mp3",
  "w8_q1_p": "/assets/audio/w8_q1_p.mp3",
  "w8_q1_h": "/assets/audio/w8_q1_h.mp3",
  "w8_q2_p": "/assets/audio/w8_q2_p.mp3",
  "w8_q2_h": "/assets/audio/w8_q2_h.mp3",
  "w8_q3_p": "/assets/audio/w8_q3_p.mp3",
  "w8_q3_h": "/assets/audio/w8_q3_h.mp3",
  "w8_q4_p": "/assets/audio/w8_q4_p.mp3",
  "w8_q4_h": "/assets/audio/w8_q4_h.mp3",
  "w8_q5_p": "/assets/audio/w8_q5_p.mp3",
  "w8_q5_h": "/assets/audio/w8_q5_h.mp3",
  "w8_q6_p": "/assets/audio/w8_q6_p.mp3",
  "w8_q6_h": "/assets/audio/w8_q6_h.mp3",
  "w8_q7_p": "/assets/audio/w8_q7_p.mp3",
  "w8_q7_h": "/assets/audio/w8_q7_h.mp3",
  "w8_q8_p": "/assets/audio/w8_q8_p.mp3",
  "w8_q8_h": "/assets/audio/w8_q8_h.mp3",
  "w8_q9_p": "/assets/audio/w8_q9_p.mp3",
  "w8_q9_h": "/assets/audio/w8_q9_h.mp3",
  "w8_q10_p": "/assets/audio/w8_q10_p.mp3",
  "w8_q10_h": "/assets/audio/w8_q10_h.mp3",
  "w9_q1_p": "/assets/audio/w9_q1_p.mp3",
  "w9_q1_h": "/assets/audio/w9_q1_h.mp3",
  "w9_q2_p": "/assets/audio/w9_q2_p.mp3",
  "w9_q2_h": "/assets/audio/w9_q2_h.mp3",
  "w9_q3_p": "/assets/audio/w9_q3_p.mp3",
  "w9_q3_h": "/assets/audio/w9_q3_h.mp3",
  "w9_q4_p": "/assets/audio/w9_q4_p.mp3",
  "w9_q4_h": "/assets/audio/w9_q4_h.mp3",
  "w9_q5_p": "/assets/audio/w9_q5_p.mp3",
  "w9_q5_h": "/assets/audio/w9_q5_h.mp3",
  "w9_q6_p": "/assets/audio/w9_q6_p.mp3",
  "w9_q6_h": "/assets/audio/w9_q6_h.mp3",
  "w9_q7_p": "/assets/audio/w9_q7_p.mp3",
  "w9_q7_h": "/assets/audio/w9_q7_h.mp3",
  "w9_q8_p": "/assets/audio/w9_q8_p.mp3",
  "w9_q8_h": "/assets/audio/w9_q8_h.mp3",
  "w9_q9_p": "/assets/audio/w9_q9_p.mp3",
  "w9_q9_h": "/assets/audio/w9_q9_h.mp3",
  "w9_q10_p": "/assets/audio/w9_q10_p.mp3",
  "w9_q10_h": "/assets/audio/w9_q10_h.mp3",
  "w10_q1_p": "/assets/audio/w10_q1_p.mp3",
  "w10_q1_h": "/assets/audio/w10_q1_h.mp3",
  "w10_q2_p": "/assets/audio/w10_q2_p.mp3",
  "w10_q2_h": "/assets/audio/w10_q2_h.mp3",
  "w10_q3_p": "/assets/audio/w10_q3_p.mp3",
  "w10_q3_h": "/assets/audio/w10_q3_h.mp3",
  "w10_q4_p": "/assets/audio/w10_q4_p.mp3",
  "w10_q4_h": "/assets/audio/w10_q4_h.mp3",
  "w10_q5_p": "/assets/audio/w10_q5_p.mp3",
  "w10_q5_h": "/assets/audio/w10_q5_h.mp3",
  "w10_q6_p": "/assets/audio/w10_q6_p.mp3",
  "w10_q6_h": "/assets/audio/w10_q6_h.mp3",
  "w10_q7_p": "/assets/audio/w10_q7_p.mp3",
  "w10_q7_h": "/assets/audio/w10_q7_h.mp3",
  "w10_q8_p": "/assets/audio/w10_q8_p.mp3",
  "w10_q8_h": "/assets/audio/w10_q8_h.mp3",
  "w10_q9_p": "/assets/audio/w10_q9_p.mp3",
  "w10_q9_h": "/assets/audio/w10_q9_h.mp3",
  "w10_q10_p": "/assets/audio/w10_q10_p.mp3",
  "w10_q10_h": "/assets/audio/w10_q10_h.mp3"
};
